import type { KnipConfig } from "knip";

const config: KnipConfig = {
	workspaces: {
		".": {
			entry: [],
			project: [],
		},
		"apps/backend": {
			entry: ["src/index.ts"],
			project: ["src/**/*.ts"],
		},
		"apps/frontend": {
			entry: ["app/**/*.{ts,tsx}", "ui/**/*.{ts,tsx}"],
			project: ["app/**/*.{ts,tsx}", "ui/**/*.{ts,tsx}"],
		},
		"apps/backoffice": {
			entry: ["app/**/*.{ts,tsx}", "ui/**/*.{ts,tsx}", "proxy.ts"],
			project: ["app/**/*.{ts,tsx}", "ui/**/*.{ts,tsx}"],
		},
		"packages/ui": {
			entry: ["src/index.ts"],
			project: ["src/**/*.{ts,tsx}"],
		},
		"packages/app-types": {
			entry: ["src/index.ts"],
			project: ["src/**/*.ts"],
		},
		"packages/utils": {
			entry: ["src/index.ts"],
			project: ["src/**/*.ts"],
		},
	},
	// @prisma/client is used by the generated client in src/generated/
	// tailwindcss is consumed via PostCSS plugin (@tailwindcss/postcss), not via JS imports
	// @deck.gl/react is intentionally kept as a future dependency
	// @repo/utils is intentionally kept in backoffice for future use
	ignoreDependencies: [
		"@prisma/client",
		"tailwindcss",
		"@deck.gl/react",
		"@repo/utils",
	],
	// Exports used only within the same file/package (e.g. internal helpers)
	ignoreExportsUsedInFile: true,
	// prisma.config.ts requires DATABASE_URL at load time — not available in CI lint jobs
	// packages/typescript-config contains tsconfig JSON files referencing Next.js plugin
	// (reported as unresolved import "next", which is a false positive for tsconfig plugins)
	// src/generated is auto-generated by Prisma and not part of the source graph
	ignore: [
		"apps/backend/prisma.config.ts",
		"apps/backend/src/generated/**",
		"packages/typescript-config/**",
	],
};

export default config;
